testguru #1
aik-stok/testguru pull request #1
Opened 2017-12-14 10:54 UTC by aik-stok

2017-12-14 20:37 UTC, psylone requested changes

2017-12-14 20:37 UTC, psylone commented on README.md
> + Fire, house, mouse, car, spring.
Пожалуйста поясни, за что отвечает в проекте каждая из перечисленных сущностей?

2017-12-14 20:37 UTC, psylone commented on app/controllers/static_pages_controller.rb
> +end
Статика отдаётся Rails из каталога `public` автоматически. Это происходит ещё до того момента как запрос достигнет самого приложения, а значит будет работать быстрее.

2017-12-14 20:37 UTC, psylone commented on app/views/static_pages/about.html.erb
> + <p> <a href = thinknetica.com> Thinknetica </a> </p>
Пожалуйста сделай так чтобы ссылка открывалась в новой вкладке. Также проверь корректность определения значения атрибута HTML элемента. Подробнее можно посмотреть [здесь](https://developer.mozilla.org/ru/docs/Learn/Getting_started_with_the_web/HTML_basics).

2017-12-14 20:37 UTC, psylone commented on config/initializers/version.rb
> +
Поскольку константа версии относится к приложения, её стоит определить в области видимости модуля приложения, вместо глобальной области видимости. Должно работать примерно так:

```ruby
TestGuru.version # => '0.1'
```

Также посмотри [Semantic Versioning](https://semver.org). Этот подход крайне широко применяется в настоящее время.

2017-12-14 20:37 UTC, psylone commented on config/routes.rb
> +  get 'about/author' => 'static_pages#author'
В этих маршрутах нет необходимости, поскольку требуется отдавать статические страницы. Их Rails умеет автоматически отдавать из каталога `public`, а также вложенных в него каталогов.

2017-12-15 00:28 UTC, psylone approved these changes

2017-12-15 00:28 UTC, psylone commented on public/about.html
> + <p> <a target="_blank" href = http://thinknetica.com> Thinknetica </a> </p>
Значение `href` тоже нужно заключить в кавычки и убрать пробелы вокруг `=`.

2017-12-15 00:28 UTC, psylone commented on config/application.rb
> +  config.time_zone = 'Minsk'
Нужно будет добавить конфигурацию локали по умолчанию.

2017-12-15 00:28 UTC, psylone commented on app/controllers/static_pages_controller.rb
> +class StaticPagesController < ApplicationController
В этом контроллере теперь нет необходимости.

2017-12-15 07:02 UTC, aik-stok commented on config/application.rb
> +  config.time_zone = 'Minsk'
enforce_available_locales!': :ru is not a valid locale (I18n::InvalidLocale)
Не подгружает локаль вовремя. отключил enforse.

2017-12-15 07:02 UTC, merged

2017-12-15 12:06 UTC, psylone commented on config/application.rb
> +  config.time_zone = 'Minsk'
Думаю, нужен файл локализации чтобы локаль оказалась доступной.

2017-12-15 12:11 UTC, aik-stok commented on config/application.rb
> +  config.time_zone = 'Minsk'
Файл есть причем, полноценный....

2017-12-15 12:28 UTC, psylone commented on config/application.rb
> +  config.time_zone = 'Minsk'
А, ну да. Из-за особенностей инициализации и загрузки Rails приложения, локаль нужно устанавливать через метод `config`, а не через модуль `I18n` напрямую.