Develope 11
aik-stok/testguru pull request #11
Opened 2018-02-23 13:39 UTC by aik-stok

2018-02-24 01:37 UTC, psylone requested changes

2018-02-24 01:37 UTC, psylone commented on app/controllers/application_controller.rb
> +  before_action :different_locale?
Предполагается что метод с `?` это предикат который возвращает `true` или `false`. Для обратного вызова такой нэйминг не годится.

2018-02-24 01:37 UTC, psylone commented on app/controllers/application_controller.rb
> +    define_singleton_method(:default_url_options) {{lang: I18n.locale}} if I18n.locale != I18n.default_locale
Это слишком сложно )

Достаточно **переопределить** метод `default_url_options`.

2018-02-24 01:37 UTC, psylone commented on app/helpers/assignment_helper.rb
> +      t(:success_flash_message)
Обычно используют строки в качестве аргумента метода `t`.

2018-02-24 01:37 UTC, psylone commented on app/views/devise/_links.erb
> +<% ActiveSupport::Deprecation.warn "Rendering partials devise/_links.erb is deprecated" \
Смотри, это депрекейтед фрагмент, лучше использовать то что предлагается: `devise/shared/links`.

2018-02-24 01:37 UTC, psylone commented on app/views/devise/registrations/edit.html.erb
> +<%= form_for(resource, :as => resource_name, :url => registration_path(resource_name), :html => { :method => :put }) do |f| %>
Тот вариант который был гораздо лучше. Он более новый и его всегда используют когда ключи хэша являются символами.

2018-02-24 01:37 UTC, psylone commented on app/views/devise/registrations/new.html.erb
> +<h2><%= t('.sign_up', :default => "Sign up") %></h2>
Используй общепринятый синтаксис для хэшей когда ключи являются символами: `default: 'Sign up'`.

2018-02-24 01:37 UTC, psylone commented on config/locales/ru.yml
> +  fail_flash_message: " ответов правильно. Провал"
Лучше определить ключ `flash` и под ним `fail` и `success`:

```yaml
ru:
  flash:
    success: "good"
    fail: "bad"
```

2018-02-24 20:54 UTC, aik-stok commented on config/locales/ru.yml
> +  fail_flash_message: " ответов правильно. Провал"
Не совсем понял. Что значит flash:  ?
Хэлпер у меня называется flashmessage. 
Если я в локали пишу так:
ru:
  flash_message:
    success_flash_message:"good"
    fail_flash_message: "bad"
оно просто не подхватывается. а если просто в корень, то все гуд...

2018-02-25 00:02 UTC, psylone approved these changes

2018-02-27 22:57 UTC, psylone commented on config/locales/ru.yml
> +  fail_flash_message: " ответов правильно. Провал"
Это же YAML-файл, нужны отступы:

```yaml
ru:
  flash:
    success: "good"
    fail: "bad"
```

2018-02-28 16:14 UTC, merged