Creation association
aik-stok/testguru pull request #4
Opened 2017-12-23 08:29 UTC by aik-stok

2017-12-23 17:38 UTC, psylone requested changes
Комментарии: https://go.teachbase.ru/courses/13268/tasks/9172#user_id=125457&session_id=45733

2017-12-24 22:46 UTC, psylone approved these changes

2017-12-24 22:46 UTC, psylone commented on app/models/test.rb
> +  has_many :users, through: :assignments
Ну, а `has_many :assignments` где? Как иначе ActiveRecord сможет построить запрос? Поэкспериментируй в rails-коносли и посмотри какой формируется SQL запрос.

2017-12-24 22:46 UTC, psylone commented on app/models/test.rb
> +  belongs_to :user
Лучше назвать ассоциацию `belongs_to :author`, чтобы было понятно что это за пользователь такой.

2017-12-24 22:46 UTC, psylone commented on app/models/test.rb
> +  belongs_to :user
Кроме того, на стороне пользователя тоже должна быть ассоциация для выбора всех тестов которые он создал.

2018-01-11 18:46 UTC, aik-stok commented
Не влом, глянь, плиз, нормально ли связь для определения авторства сделал?

2018-01-11 21:44 UTC, psylone commented
> Не влом, глянь, плиз, нормально ли связь для определения авторства сделал?

Да, вполне.

2018-01-12 20:56 UTC, merged