view and helpers implementation
aik-stok/testguru pull request #7
Opened 2018-01-24 08:57 UTC by aik-stok

2018-01-25 00:12 UTC, psylone requested changes

2018-01-25 00:12 UTC, psylone commented on app/controllers/questions_controller.rb
>    def index
Поскольку список вопросов должен выводиться на странице просмотра теста, этот метод не нужен.

2018-01-25 00:12 UTC, psylone commented on app/controllers/questions_controller.rb
> +    p params
Это явно лишнее )

2018-01-25 00:12 UTC, psylone commented on app/controllers/questions_controller.rb
>      @question = Question.find(params[:id]).destroy
Есть обратный вызов `find_question`.

2018-01-25 00:12 UTC, psylone commented on app/helpers/application_helper.rb
> +    Date.today.year
Стоит использовать `Date.current`, чтобы учитывать часовой пояс из конфигурации приложения.

2018-01-25 00:12 UTC, psylone commented on app/helpers/application_helper.rb
> +    link_to "TestGuru", "https://github.com/#{author}/#{repo}"
Репозиторий не обязательно называется TestGuru, это может быть и `github_url('rails', 'rails')`.

2018-01-25 00:12 UTC, psylone commented on app/helpers/questions_helper.rb
> +    if @question.body.nil?
Лучше использовать метод `new_record?`

2018-01-25 00:12 UTC, psylone commented on app/helpers/questions_helper.rb
> +  def question_header
Стоит передавать вопрос в параметре метода чтобы сделать код менее связанным. Тест всегда можно получить по ассоциации `question.test`, даже если вопрос ещё не был сохранён в базе данных.

2018-01-25 00:12 UTC, psylone commented on app/helpers/application_helper.rb
> +    link_to "TestGuru", "https://github.com/#{author}/#{repo}"
Стоит добавить опцию чтобы ссылка открывалась в новой вкладке.

2018-01-25 00:12 UTC, psylone commented on app/views/layouts/_footer.html.erb
> +    <p><%= link_to "Учебный проект в онлайн-школе Thinknetica", 'http://thinknetica.com' %>
Стоит сделать так чтобы ссылка открывалась в новой вкладке.

2018-01-25 00:12 UTC, psylone commented on app/views/layouts/application.html.erb
> +      </div>
Почему бы `<div>` не поместить внутри фрагмента представления.

2018-01-25 00:12 UTC, psylone commented on app/views/questions/edit.html.erb
> +<%= form_with model: @question, local: true do |f| %>
`model: [@test, @question]` будет вести себя корректно даже если `@test` возвращает значение `nil`.

2018-01-25 00:12 UTC, psylone commented on app/views/questions/index.html.erb
>  <h1>Questions</h1>
Этот шаблон больше не нужен.

2018-01-25 00:12 UTC, psylone commented on app/views/shared/_questions.html.erb
> +<% @questions.each do|question| %>
Стоит сделать фрагмент который рендерит один вопрос и использовать рендеринг коллекции.

2018-01-25 00:12 UTC, psylone commented on app/views/shared/_questions.html.erb
> +<% @questions.each do|question| %>
Также лучше поместить фрагмент в каталог с ресурсом вопросов, поскольку именно они рендерятся.

2018-01-26 01:07 UTC, psylone approved these changes

2018-01-26 01:07 UTC, psylone commented on app/helpers/questions_helper.rb
> +      "Create New #{question.test.title} Question"
👍

2018-01-26 01:07 UTC, psylone commented on app/views/layouts/_footer.html.erb
> +      <p><%= link_to "Учебный проект в онлайн-школе Thinknetica", 'http://thinknetica.com' %>
`target: :_blank` )

2018-01-26 01:07 UTC, psylone commented on app/views/shared/_form_for_questions.html.erb
> +<%= link_to 'Back to tests', tests_path %>
Форму тоже лучше поместить в каталог `app/views/questions`.

2018-01-26 01:07 UTC, psylone commented on app/views/questions/_question.html.erb
> +</table>
Получается что для каждого вопроса будет создаваться новая таблица. Это оверхед. Стоит в шаблоне просмотра теста задать таблицу и строку с заголовками таблицы, а в этом фрагменте выводить только строку `<tr>` для каждого вопроса. В шаблоне просмотра теста будет примерно так:

```ruby
<!-- app/views/tests/show.html.erb -->
<table>
  <tr>
    <th>Body</th>
    <th colspan="2">Actions</th>
  </tr>

  <%= render @test.questions %>
</table>
```

2018-01-26 08:21 UTC, aik-stok commented on app/views/layouts/_footer.html.erb
> +      <p><%= link_to "Учебный проект в онлайн-школе Thinknetica", 'http://thinknetica.com' %>
Вроде ж делал и сохранял....Что-то серьезно не так с этим BBEdit.....

2018-01-26 09:07 UTC, aik-stok commented on app/views/questions/_question.html.erb
> +</table>
У меня плавится мозг. Как вот это — <%= render partial: 'questions/question', collection: @questions %>, может заменить это — <%= render @test.questions %>???
Как эта магия работает?

2018-01-26 09:07 UTC, aik-stok commented on app/views/questions/_question.html.erb
> +</table>
Как подхватываются паршалы?...

2018-01-26 09:19 UTC, merged

2018-01-29 03:02 UTC, psylone commented on app/views/questions/_question.html.erb
> +</table>
Rails динамически определяет класс каждого объекта из коллекции и на основе имени класса ищет фрагмент.